### ISSUE TITLE
docker: repository name must be lowercase

### ISSUE THREAD

**Issue by clairetn** [BioinformaticsLabAtMUN/sRNA-Detect#2]
Hi,
I'd like to use your sRNA-Detect workflow but when I run `docker pull penacastillolab/sRNA-Detect` it reply `invalid reference format: repository name must be lowercase`.

**Comment by BioinformaticsLabAtMUN** [comment]
Hi,
Thank you for reporting this. The repository name in the instructions has been corrected.
